# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'keen_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for keen_app
  pod 'Alamofire'

  target 'keen_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'keen_appUITests' do
    # Pods for testing
  end

end
